# Site Configuration
title: "Awesome Incident Postmortems"
description: "A curated list of incident postmortem documents from major technology companies and service providers"
url: "https://awesome-incident.gapra.id"
baseurl: "/"
author: "ggalihpp"

# Theme and Appearance
theme: minima

# Build Settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Default layouts - simplified
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .git/
  - .github/
  - README.md

# SEO
title_separator: "|"

# Minima Theme Customization
minima:
  date_format: "%b %-d, %Y"
